version: '3'
services:
  api:
    build: ./api
    depends_on:
      - opa
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - frontend_network

  frontend:
    build: ./frontend/csaMessageApp
    depends_on:
      - api
      - opa
    env_file:
      - .env
    ports:
      - "4200:80"
    networks:
      - frontend_network
      - backend_network

  opa:
    image: openpolicyagent/opa
    command: ["run", "--server", "--addr", ":8181", "/policy.Rego"]
    volumes:
      - ./opa/policy.Rego:/policy.Rego:ro
    networks:
      - frontend_network
      - backend_network


networks:
  frontend_network:
  backend_network: